name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Run Test Build
    - name: Run Gradle Tests
      run: ./gradlew test

    # Run Build Project
    - name: Build with Gradle
      run: ./gradlew build

    # Create APK Debug
    - name: Build apk debug (APK)
      run: ./gradlew assembleDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with: 
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.6.0
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        file: app/build/outputs/apk/debug/*.apk
        groups: developer
        releaseNotes: ${{ github.event.head_commit.message }}
        debug: true
